DROP TABLE IF EXISTS EMPLOYER;
CREATE TABLE EMPLOYER (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50),
	LINKEDIN VARCHAR(50),
	WEBSITE VARCHAR(50)
);

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	EMPLOYER_ID INT,
	LINKEDIN VARCHAR(50),
	SKILLS VARCHAR(50)
);